### ISSUE TITLE
Backbone doesn't work

### ISSUE THREAD

**Issue by marissennet-pull** [aut0poietic/wp-admin-modal-example#2]
content/plugins/modal-backbone/modal.php:83 should be.

    wp_enqueue_script( 'backbone_modal' , $base . 'js/modal.js' , array( 'backbone', 'jquery' ) );

Else the error is given that backbone isn't definded

But now the following error is created
![backbone error](https://cloud.githubusercontent.com/assets/4599031/5660267/93397f40-971e-11e4-9977-4ac7f5ba353a.png)

I have no idea what that means.

WP 4.1

**Comment by aut0poietic** [comment]
The `wp_enqueue_script()` called within the `edit.php` or `post-new.php` so backbone should already be included by default by the media framework -- at least in previous versions of WordPress. 

Adding  `'backbone'` to the enqueue call normally wouldn't hurt anything, except that this is pretty old code. Underscore ( which is included implicitly ) changed a few dot-revisions back so that the second parameter to [_.bindAll()](http://underscorejs.org/#bindAll) is now required.

**Comment by bora89** [comment]
I have WP 4.0 and the same issue. First backbone.js is not defined, then if I use wp_enqueue_script( 'backbone_modal' , $base . 'js/modal.js' , array( 'backbone', 'jquery' ) ); "Uncaught Error: bindAll must be passed function names". How and where to fix it?

**Comment by aut0poietic** [comment]
Patched in v1.0.1
